### ISSUE TITLE
Building a CA fail

### ISSUE THREAD

**Issue by Maagoul** [r509/r509#113]
I am CA but it fail always in generating serial steps I execute the r509 --out root.cer --keyout root.key then I put my parameters but always it throw me this 👍 

/usr/local/lib/ruby/gems/2.0.0/gems/r509-0.10.0/lib/r509/certificate_authority/signer.rb:146:in `to_s': OpenSSL::BNError
    from /usr/local/lib/ruby/gems/2.0.0/gems/r509-0.10.0/lib/r509/certificate_authority/signer.rb:146:in `create_serial'
    from /usr/local/lib/ruby/gems/2.0.0/gems/r509-0.10.0/lib/r509/certificate_authority/signer.rb:130:in `build_cert'
    from /usr/local/lib/ruby/gems/2.0.0/gems/r509-0.10.0/lib/r509/certificate_authority/signer.rb:81:in `selfsign'
    from /usr/local/lib/ruby/gems/2.0.0/gems/r509-0.10.0/bin/r509:111:in `<top (required)>'
    from /usr/local/bin/r509:23:in `load'
    from /usr/local/bin/r509:23:in `<main>'

**Comment by reaperhulk** [comment]
Try running this script on your system and see what the output is:

```ruby
require 'openssl'

rand = OpenSSL::BN.rand(96,0) # 96 bits is 12 bytes (octets).
serial = OpenSSL::BN.new((Time.now.to_f*1000000).to_i.to_s + rand.to_s)
puts serial.to_s
```

This is extracted from the code that failed https://github.com/r509/r509/blob/761e7141663dc7da047e0a356ab29649dd9ecadd/lib/r509/certificate_authority/signer.rb#L146
