### ISSUE TITLE
Not Support For Ruby 2.4.0

### ISSUE THREAD

**Issue by zhangjiha** [r509/r509#127]
When I run  R509::Cert::Extensions::BasicConstraints.new(ca: false), raise Error 
NoMethodError: undefined method `value' for nil:NilClass
	from /Users/zhangji/.rvm/gems/ruby-2.4.0/gems/r509-1.0.1/lib/r509/asn1.rb:20:in `get_extension_payload'
	from /Users/zhangji/.rvm/gems/ruby-2.4.0/gems/r509-1.0.1/lib/r509/cert/extensions/basic_constraints.rb:67:in `parse_extension'
	from /Users/zhangji/.rvm/gems/ruby-2.4.0/gems/r509-1.0.1/lib/r509/cert/extensions/basic_constraints.rb:33:in `initialize'
	from (irb):14:in `new'
	from (irb):14
	from /Users/zhangji/.rvm/rubies/ruby-2.4.0/bin/irb:11:in `<main>'

**Comment by zhangjiha** [comment]
I change 
**OpenSSL::ASN1.decode(asn.entries.last.value).value** 
to 
**OpenSSL::ASN1.decode(asn.value.last.value).value** 
in asn1.rb, and it is OK.
I think the reason is that ruby 2.4.0 is not support entries by value instance value

**Comment by reaperhulk** [comment]
If you can write a patch to support both Ruby 2.4 and older Ruby I will review it. Thank you for investigating.
